package request

import (
	"context"
	"errors"
	"log/slog"
	"testing"

	"github.com/google/go-cmp/cmp"
	apiv2 "github.com/metal-stack/api/go/metalstack/api/v2"
	"github.com/metal-stack/api/go/metalstack/infra/v2/infrav2connect"
	"github.com/metal-stack/metal-apiserver/pkg/repository"
	"github.com/stretchr/testify/require"
)

func Test_opa_getTokenPermissions(t *testing.T) {
	tests := []struct {
		name               string
		token              *apiv2.Token
		projectsAndTenants *repository.ProjectsAndTenants
		want               tokenPermissions
		wantErr            error
	}{
		{
			name:    "unknown admin role",
			token:   &apiv2.Token{AdminRole: apiv2.AdminRole_ADMIN_ROLE_UNSPECIFIED.Enum()},
			wantErr: errors.New("given admin role:ADMIN_ROLE_UNSPECIFIED is not valid"),
		},
		{
			name:  "empty token",
			token: nil,
			want: tokenPermissions{
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      {"*": true},
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": {"*": true},
				"/metalstack.api.v2.HealthService/Get":                           {"*": true},
				"/metalstack.api.v2.MethodService/List":                          {"*": true},
				"/metalstack.api.v2.VersionService/Get":                          {"*": true},
			},
		},
		{
			name: "admin role editor",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				AdminRole: apiv2.AdminRole_ADMIN_ROLE_EDITOR.Enum(),
			},
			want: tokenPermissions{
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      {"*": true},
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": {"*": true},
				"/metalstack.admin.v2.FilesystemService/Create":                  {"*": true},
				"/metalstack.admin.v2.FilesystemService/Delete":                  {"*": true},
				"/metalstack.admin.v2.FilesystemService/Update":                  {"*": true},
				"/metalstack.admin.v2.IPService/List":                            {"*": true},
				"/metalstack.admin.v2.ImageService/Create":                       {"*": true},
				"/metalstack.admin.v2.ImageService/Delete":                       {"*": true},
				"/metalstack.admin.v2.ImageService/Update":                       {"*": true},
				"/metalstack.admin.v2.ImageService/Usage":                        {"*": true},
				"/metalstack.admin.v2.MachineService/Get":                        {"*": true},
				"/metalstack.admin.v2.MachineService/List":                       {"*": true},
				"/metalstack.admin.v2.NetworkService/Create":                     {"*": true},
				"/metalstack.admin.v2.NetworkService/Delete":                     {"*": true},
				"/metalstack.admin.v2.NetworkService/Get":                        {"*": true},
				"/metalstack.admin.v2.NetworkService/List":                       {"*": true},
				"/metalstack.admin.v2.NetworkService/Update":                     {"*": true},
				"/metalstack.admin.v2.PartitionService/Capacity":                 {"*": true},
				"/metalstack.admin.v2.PartitionService/Create":                   {"*": true},
				"/metalstack.admin.v2.PartitionService/Delete":                   {"*": true},
				"/metalstack.admin.v2.PartitionService/Update":                   {"*": true},
				"/metalstack.admin.v2.SizeService/Create":                        {"*": true},
				"/metalstack.admin.v2.SizeService/Delete":                        {"*": true},
				"/metalstack.admin.v2.SizeService/Update":                        {"*": true},
				"/metalstack.admin.v2.SwitchService/Delete":                      {"*": true},
				"/metalstack.admin.v2.SwitchService/Get":                         {"*": true},
				"/metalstack.admin.v2.SwitchService/List":                        {"*": true},
				"/metalstack.admin.v2.SwitchService/Migrate":                     {"*": true},
				"/metalstack.admin.v2.SwitchService/Port":                        {"*": true},
				"/metalstack.admin.v2.SwitchService/Update":                      {"*": true},
				"/metalstack.admin.v2.TenantService/Create":                      {"*": true},
				"/metalstack.admin.v2.TenantService/List":                        {"*": true},
				"/metalstack.admin.v2.TokenService/Create":                       {"*": true},
				"/metalstack.admin.v2.TokenService/List":                         {"*": true},
				"/metalstack.admin.v2.TokenService/Revoke":                       {"*": true},
				"/metalstack.api.v2.FilesystemService/Get":                       {"*": true},
				"/metalstack.api.v2.FilesystemService/List":                      {"*": true},
				"/metalstack.api.v2.FilesystemService/Match":                     {"*": true},
				"/metalstack.api.v2.HealthService/Get":                           {"*": true},
				"/metalstack.api.v2.IPService/Create":                            {"*": true},
				"/metalstack.api.v2.IPService/Delete":                            {"*": true},
				"/metalstack.api.v2.IPService/Get":                               {"*": true},
				"/metalstack.api.v2.IPService/List":                              {"*": true},
				"/metalstack.api.v2.IPService/Update":                            {"*": true},
				"/metalstack.api.v2.ImageService/Get":                            {"*": true},
				"/metalstack.api.v2.ImageService/Latest":                         {"*": true},
				"/metalstack.api.v2.ImageService/List":                           {"*": true},
				"/metalstack.api.v2.MachineService/Create":                       {"*": true},
				"/metalstack.api.v2.MachineService/Delete":                       {"*": true},
				"/metalstack.api.v2.MachineService/Get":                          {"*": true},
				"/metalstack.api.v2.MachineService/List":                         {"*": true},
				"/metalstack.api.v2.MachineService/Update":                       {"*": true},
				"/metalstack.api.v2.MethodService/List":                          {"*": true},
				"/metalstack.api.v2.MethodService/TokenScopedList":               {"*": true},
				"/metalstack.api.v2.NetworkService/Create":                       {"*": true},
				"/metalstack.api.v2.NetworkService/Delete":                       {"*": true},
				"/metalstack.api.v2.NetworkService/Get":                          {"*": true},
				"/metalstack.api.v2.NetworkService/List":                         {"*": true},
				"/metalstack.api.v2.NetworkService/ListBaseNetworks":             {"*": true},
				"/metalstack.api.v2.NetworkService/Update":                       {"*": true},
				"/metalstack.api.v2.PartitionService/Get":                        {"*": true},
				"/metalstack.api.v2.PartitionService/List":                       {"*": true},
				"/metalstack.api.v2.ProjectService/Create":                       {"*": true},
				"/metalstack.api.v2.ProjectService/Delete":                       {"*": true},
				"/metalstack.api.v2.ProjectService/Get":                          {"*": true},
				"/metalstack.api.v2.ProjectService/Invite":                       {"*": true},
				"/metalstack.api.v2.ProjectService/InviteAccept":                 {"*": true},
				"/metalstack.api.v2.ProjectService/InviteDelete":                 {"*": true},
				"/metalstack.api.v2.ProjectService/InviteGet":                    {"*": true},
				"/metalstack.api.v2.ProjectService/InvitesList":                  {"*": true},
				"/metalstack.api.v2.ProjectService/Leave":                        {"*": true},
				"/metalstack.api.v2.ProjectService/List":                         {"*": true},
				"/metalstack.api.v2.ProjectService/RemoveMember":                 {"*": true},
				"/metalstack.api.v2.ProjectService/Update":                       {"*": true},
				"/metalstack.api.v2.ProjectService/UpdateMember":                 {"*": true},
				"/metalstack.api.v2.SizeService/Get":                             {"*": true},
				"/metalstack.api.v2.SizeService/List":                            {"*": true},
				"/metalstack.api.v2.TenantService/Create":                        {"*": true},
				"/metalstack.api.v2.TenantService/Delete":                        {"*": true},
				"/metalstack.api.v2.TenantService/Get":                           {"*": true},
				"/metalstack.api.v2.TenantService/Invite":                        {"*": true},
				"/metalstack.api.v2.TenantService/InviteAccept":                  {"*": true},
				"/metalstack.api.v2.TenantService/InviteDelete":                  {"*": true},
				"/metalstack.api.v2.TenantService/InviteGet":                     {"*": true},
				"/metalstack.api.v2.TenantService/InvitesList":                   {"*": true},
				"/metalstack.api.v2.TenantService/Leave":                         {"*": true},
				"/metalstack.api.v2.TenantService/List":                          {"*": true},
				"/metalstack.api.v2.TenantService/RemoveMember":                  {"*": true},
				"/metalstack.api.v2.TenantService/Update":                        {"*": true},
				"/metalstack.api.v2.TenantService/UpdateMember":                  {"*": true},
				"/metalstack.api.v2.TokenService/Create":                         {"*": true},
				"/metalstack.api.v2.TokenService/Get":                            {"*": true},
				"/metalstack.api.v2.TokenService/List":                           {"*": true},
				"/metalstack.api.v2.TokenService/Refresh":                        {"*": true},
				"/metalstack.api.v2.TokenService/Revoke":                         {"*": true},
				"/metalstack.api.v2.TokenService/Update":                         {"*": true},
				"/metalstack.api.v2.UserService/Get":                             {"*": true},
				"/metalstack.api.v2.VersionService/Get":                          {"*": true},
				"/metalstack.infra.v2.BMCService/UpdateBMCInfo":                  {"*": true},
				"/metalstack.infra.v2.SwitchService/Get":                         {"*": true},
				"/metalstack.infra.v2.SwitchService/Heartbeat":                   {"*": true},
				"/metalstack.infra.v2.SwitchService/Register":                    {"*": true},
			},
			wantErr: nil,
		},
		{
			name: "admin role viewer",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				AdminRole: apiv2.AdminRole_ADMIN_ROLE_VIEWER.Enum(),
			},
			want: tokenPermissions{
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      {"*": true},
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": {"*": true},
				"/metalstack.admin.v2.IPService/List":                            {"*": true},
				"/metalstack.admin.v2.ImageService/Usage":                        {"*": true},
				"/metalstack.admin.v2.MachineService/Get":                        {"*": true},
				"/metalstack.admin.v2.MachineService/List":                       {"*": true},
				"/metalstack.admin.v2.NetworkService/Get":                        {"*": true},
				"/metalstack.admin.v2.NetworkService/List":                       {"*": true},
				"/metalstack.admin.v2.PartitionService/Capacity":                 {"*": true},
				"/metalstack.admin.v2.SwitchService/Get":                         {"*": true},
				"/metalstack.admin.v2.SwitchService/List":                        {"*": true},
				"/metalstack.admin.v2.TenantService/List":                        {"*": true},
				"/metalstack.admin.v2.TokenService/List":                         {"*": true},
				"/metalstack.api.v2.FilesystemService/Get":                       {"*": true},
				"/metalstack.api.v2.FilesystemService/List":                      {"*": true},
				"/metalstack.api.v2.FilesystemService/Match":                     {"*": true},
				"/metalstack.api.v2.HealthService/Get":                           {"*": true},
				"/metalstack.api.v2.IPService/Get":                               {"*": true},
				"/metalstack.api.v2.IPService/List":                              {"*": true},
				"/metalstack.api.v2.ImageService/Get":                            {"*": true},
				"/metalstack.api.v2.ImageService/Latest":                         {"*": true},
				"/metalstack.api.v2.ImageService/List":                           {"*": true},
				"/metalstack.api.v2.MachineService/Get":                          {"*": true},
				"/metalstack.api.v2.MachineService/List":                         {"*": true},
				"/metalstack.api.v2.MethodService/List":                          {"*": true},
				"/metalstack.api.v2.MethodService/TokenScopedList":               {"*": true},
				"/metalstack.api.v2.NetworkService/Get":                          {"*": true},
				"/metalstack.api.v2.NetworkService/List":                         {"*": true},
				"/metalstack.api.v2.NetworkService/ListBaseNetworks":             {"*": true},
				"/metalstack.api.v2.PartitionService/Get":                        {"*": true},
				"/metalstack.api.v2.PartitionService/List":                       {"*": true},
				"/metalstack.api.v2.ProjectService/Get":                          {"*": true},
				"/metalstack.api.v2.ProjectService/InviteAccept":                 {"*": true},
				"/metalstack.api.v2.ProjectService/InviteGet":                    {"*": true},
				"/metalstack.api.v2.ProjectService/Leave":                        {"*": true},
				"/metalstack.api.v2.ProjectService/List":                         {"*": true},
				"/metalstack.api.v2.SizeService/Get":                             {"*": true},
				"/metalstack.api.v2.SizeService/List":                            {"*": true},
				"/metalstack.api.v2.TenantService/Create":                        {"*": true},
				"/metalstack.api.v2.TenantService/Get":                           {"*": true},
				"/metalstack.api.v2.TenantService/InviteAccept":                  {"*": true},
				"/metalstack.api.v2.TenantService/InviteGet":                     {"*": true},
				"/metalstack.api.v2.TenantService/Leave":                         {"*": true},
				"/metalstack.api.v2.TenantService/List":                          {"*": true},
				"/metalstack.api.v2.TokenService/Create":                         {"*": true},
				"/metalstack.api.v2.TokenService/Get":                            {"*": true},
				"/metalstack.api.v2.TokenService/List":                           {"*": true},
				"/metalstack.api.v2.TokenService/Refresh":                        {"*": true},
				"/metalstack.api.v2.TokenService/Revoke":                         {"*": true},
				"/metalstack.api.v2.TokenService/Update":                         {"*": true},
				"/metalstack.api.v2.UserService/Get":                             {"*": true},
				"/metalstack.api.v2.VersionService/Get":                          {"*": true},
				"/metalstack.infra.v2.SwitchService/Get":                         {"*": true},
			},
			wantErr: nil,
		},
		{
			name: "infra role editor",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				InfraRole: apiv2.InfraRole_INFRA_ROLE_EDITOR.Enum(),
			},
			want: tokenPermissions{
				"/metalstack.infra.v2.BMCService/UpdateBMCInfo": {"*": true},
				"/metalstack.infra.v2.SwitchService/Get":        {"*": true},
				"/metalstack.infra.v2.SwitchService/Heartbeat":  {"*": true},
				"/metalstack.infra.v2.SwitchService/Register":   {"*": true},
			},
		},
		{
			name: "infra role viewer",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				InfraRole: apiv2.InfraRole_INFRA_ROLE_VIEWER.Enum(),
			},
			want: tokenPermissions{
				"/metalstack.infra.v2.SwitchService/Get": {"*": true},
			},
		},
		{
			name: "only permissions",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				Permissions: []*apiv2.MethodPermission{
					{Subject: "a", Methods: []string{"/metalstack.api.v2.IPService/Create"}},
					{Subject: "a", Methods: []string{"/metalstack.api.v2.IPService/Delete"}},
					{Subject: "b", Methods: []string{"/metalstack.api.v2.IPService/Delete"}},
				},
			},
			want: tokenPermissions{
				"/metalstack.api.v2.IPService/Create": {"a": true},
				"/metalstack.api.v2.IPService/Delete": {"a": true, "b": true},
			},
		},
		{
			name: "infra permissions",
			token: &apiv2.Token{
				Permissions: []*apiv2.MethodPermission{
					{Subject: "*", Methods: []string{infrav2connect.SwitchServiceRegisterProcedure}},
				},
			},
			want: tokenPermissions{
				"/metalstack.infra.v2.SwitchService/Register": {"*": true},
			},
		},
		{
			name: "tenant roles, token type api",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				TenantRoles: map[string]apiv2.TenantRole{
					"a": apiv2.TenantRole_TENANT_ROLE_GUEST,
					"b": apiv2.TenantRole_TENANT_ROLE_EDITOR,
					"c": apiv2.TenantRole_TENANT_ROLE_OWNER,
				},
			},
			want: tokenPermissions{
				"/metalstack.api.v2.ProjectService/Create":      {"b": true, "c": true},
				"/metalstack.api.v2.TenantService/Get":          {"b": true, "a": true, "c": true},
				"/metalstack.api.v2.TenantService/Update":       {"b": true, "c": true},
				"/metalstack.api.v2.TenantService/Delete":       {"b": true, "c": true},
				"/metalstack.api.v2.TenantService/RemoveMember": {"c": true},
				"/metalstack.api.v2.TenantService/UpdateMember": {"c": true},
				"/metalstack.api.v2.TenantService/Invite":       {"c": true},
				"/metalstack.api.v2.TenantService/InviteDelete": {"c": true},
				"/metalstack.api.v2.TenantService/InvitesList":  {"c": true},
			},
		},
		{
			name: "tenant roles, token type user",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_USER,
			},
			projectsAndTenants: &repository.ProjectsAndTenants{
				TenantRoles: map[string]apiv2.TenantRole{
					"a": apiv2.TenantRole_TENANT_ROLE_GUEST,
					"b": apiv2.TenantRole_TENANT_ROLE_EDITOR,
					"c": apiv2.TenantRole_TENANT_ROLE_OWNER,
				},
			},
			want: tokenPermissions{
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      {"*": true},
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": {"*": true},
				"/metalstack.api.v2.FilesystemService/Get":                       {"*": true},
				"/metalstack.api.v2.FilesystemService/List":                      {"*": true},
				"/metalstack.api.v2.FilesystemService/Match":                     {"*": true},
				"/metalstack.api.v2.HealthService/Get":                           {"*": true},
				"/metalstack.api.v2.ImageService/Get":                            {"*": true},
				"/metalstack.api.v2.ImageService/Latest":                         {"*": true},
				"/metalstack.api.v2.ImageService/List":                           {"*": true},
				"/metalstack.api.v2.MethodService/List":                          {"*": true},
				"/metalstack.api.v2.MethodService/TokenScopedList":               {"*": true},
				"/metalstack.api.v2.PartitionService/Get":                        {"*": true},
				"/metalstack.api.v2.PartitionService/List":                       {"*": true},
				"/metalstack.api.v2.ProjectService/Create":                       {"b": true, "c": true},
				"/metalstack.api.v2.ProjectService/InviteAccept":                 {"*": true},
				"/metalstack.api.v2.ProjectService/InviteGet":                    {"*": true},
				"/metalstack.api.v2.ProjectService/List":                         {"*": true},
				"/metalstack.api.v2.SizeService/Get":                             {"*": true},
				"/metalstack.api.v2.SizeService/List":                            {"*": true},
				"/metalstack.api.v2.TenantService/Create":                        {"*": true},
				"/metalstack.api.v2.TenantService/Get":                           {"b": true, "a": true, "c": true},
				"/metalstack.api.v2.TenantService/Update":                        {"b": true, "c": true},
				"/metalstack.api.v2.TenantService/Delete":                        {"b": true, "c": true},
				"/metalstack.api.v2.TenantService/RemoveMember":                  {"c": true},
				"/metalstack.api.v2.TenantService/UpdateMember":                  {"c": true},
				"/metalstack.api.v2.TenantService/Invite":                        {"c": true},
				"/metalstack.api.v2.TenantService/InviteAccept":                  {"*": true},
				"/metalstack.api.v2.TenantService/InviteDelete":                  {"c": true},
				"/metalstack.api.v2.TenantService/InviteGet":                     {"*": true},
				"/metalstack.api.v2.TenantService/InvitesList":                   {"c": true},
				"/metalstack.api.v2.TenantService/List":                          {"*": true},
				"/metalstack.api.v2.TokenService/Create":                         {"*": true},
				"/metalstack.api.v2.TokenService/Get":                            {"*": true},
				"/metalstack.api.v2.TokenService/List":                           {"*": true},
				"/metalstack.api.v2.TokenService/Refresh":                        {"*": true},
				"/metalstack.api.v2.TokenService/Revoke":                         {"*": true},
				"/metalstack.api.v2.TokenService/Update":                         {"*": true},
				"/metalstack.api.v2.UserService/Get":                             {"*": true},
				"/metalstack.api.v2.VersionService/Get":                          {"*": true},
			},
		},
		{
			name: "project roles, token type api",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				ProjectRoles: map[string]apiv2.ProjectRole{
					"a": apiv2.ProjectRole_PROJECT_ROLE_VIEWER,
					"b": apiv2.ProjectRole_PROJECT_ROLE_EDITOR,
					"c": apiv2.ProjectRole_PROJECT_ROLE_OWNER,
				},
			},
			want: tokenPermissions{
				"/metalstack.api.v2.IPService/Get":                   {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.IPService/Create":                {"b": true, "c": true},
				"/metalstack.api.v2.IPService/Update":                {"b": true, "c": true},
				"/metalstack.api.v2.IPService/List":                  {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.IPService/Delete":                {"b": true, "c": true},
				"/metalstack.api.v2.MachineService/Get":              {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.MachineService/Create":           {"b": true, "c": true},
				"/metalstack.api.v2.MachineService/Update":           {"b": true, "c": true},
				"/metalstack.api.v2.MachineService/List":             {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.MachineService/Delete":           {"b": true, "c": true},
				"/metalstack.api.v2.NetworkService/Get":              {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.NetworkService/Create":           {"b": true, "c": true},
				"/metalstack.api.v2.NetworkService/Update":           {"b": true, "c": true},
				"/metalstack.api.v2.NetworkService/List":             {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.NetworkService/ListBaseNetworks": {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.NetworkService/Delete":           {"b": true, "c": true},
				"/metalstack.api.v2.ProjectService/Get":              {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.ProjectService/Delete":           {"c": true},
				"/metalstack.api.v2.ProjectService/Update":           {"b": true, "c": true},
				"/metalstack.api.v2.ProjectService/RemoveMember":     {"c": true},
				"/metalstack.api.v2.ProjectService/UpdateMember":     {"c": true},
				"/metalstack.api.v2.ProjectService/Invite":           {"c": true},
				"/metalstack.api.v2.ProjectService/InviteDelete":     {"c": true},
				"/metalstack.api.v2.ProjectService/InvitesList":      {"c": true},
				"/metalstack.api.v2.ProjectService/Leave":            {"a": true},
			},
		},
		{
			name: "project roles with user token",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_USER,
				User:      "user-a",
			},
			projectsAndTenants: &repository.ProjectsAndTenants{
				ProjectRoles: map[string]apiv2.ProjectRole{
					"a": apiv2.ProjectRole_PROJECT_ROLE_VIEWER,
					"b": apiv2.ProjectRole_PROJECT_ROLE_EDITOR,
					"c": apiv2.ProjectRole_PROJECT_ROLE_OWNER,
				},
			},
			want: tokenPermissions{
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      {"*": true},
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": {"*": true},
				"/metalstack.api.v2.FilesystemService/Get":                       {"*": true},
				"/metalstack.api.v2.FilesystemService/List":                      {"*": true},
				"/metalstack.api.v2.FilesystemService/Match":                     {"*": true},
				"/metalstack.api.v2.HealthService/Get":                           {"*": true},
				"/metalstack.api.v2.IPService/Get":                               {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.IPService/Create":                            {"b": true, "c": true},
				"/metalstack.api.v2.IPService/Update":                            {"b": true, "c": true},
				"/metalstack.api.v2.IPService/List":                              {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.IPService/Delete":                            {"b": true, "c": true},
				"/metalstack.api.v2.ImageService/Get":                            {"*": true},
				"/metalstack.api.v2.ImageService/Latest":                         {"*": true},
				"/metalstack.api.v2.ImageService/List":                           {"*": true},
				"/metalstack.api.v2.MachineService/Get":                          {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.MachineService/Create":                       {"b": true, "c": true},
				"/metalstack.api.v2.MachineService/Update":                       {"b": true, "c": true},
				"/metalstack.api.v2.MachineService/List":                         {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.MachineService/Delete":                       {"b": true, "c": true},
				"/metalstack.api.v2.MethodService/List":                          {"*": true},
				"/metalstack.api.v2.MethodService/TokenScopedList":               {"*": true},
				"/metalstack.api.v2.NetworkService/Get":                          {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.NetworkService/Create":                       {"b": true, "c": true},
				"/metalstack.api.v2.NetworkService/Update":                       {"b": true, "c": true},
				"/metalstack.api.v2.NetworkService/List":                         {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.NetworkService/ListBaseNetworks":             {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.NetworkService/Delete":                       {"b": true, "c": true},
				"/metalstack.api.v2.PartitionService/Get":                        {"*": true},
				"/metalstack.api.v2.PartitionService/List":                       {"*": true},
				"/metalstack.api.v2.ProjectService/Get":                          {"a": true, "b": true, "c": true},
				"/metalstack.api.v2.ProjectService/Delete":                       {"c": true},
				"/metalstack.api.v2.ProjectService/Update":                       {"b": true, "c": true},
				"/metalstack.api.v2.ProjectService/RemoveMember":                 {"c": true},
				"/metalstack.api.v2.ProjectService/UpdateMember":                 {"c": true},
				"/metalstack.api.v2.ProjectService/Invite":                       {"c": true},
				"/metalstack.api.v2.ProjectService/InviteAccept":                 {"*": true},
				"/metalstack.api.v2.ProjectService/InviteDelete":                 {"c": true},
				"/metalstack.api.v2.ProjectService/InviteGet":                    {"*": true},
				"/metalstack.api.v2.ProjectService/InvitesList":                  {"c": true},
				"/metalstack.api.v2.ProjectService/Leave":                        {"a": true},
				"/metalstack.api.v2.ProjectService/List":                         {"*": true},
				"/metalstack.api.v2.SizeService/Get":                             {"*": true},
				"/metalstack.api.v2.SizeService/List":                            {"*": true},
				"/metalstack.api.v2.TenantService/Create":                        {"*": true},
				"/metalstack.api.v2.TenantService/InviteAccept":                  {"*": true},
				"/metalstack.api.v2.TenantService/InviteGet":                     {"*": true},
				"/metalstack.api.v2.TenantService/List":                          {"*": true},
				"/metalstack.api.v2.TokenService/Create":                         {"*": true},
				"/metalstack.api.v2.TokenService/Get":                            {"*": true},
				"/metalstack.api.v2.TokenService/List":                           {"*": true},
				"/metalstack.api.v2.TokenService/Refresh":                        {"*": true},
				"/metalstack.api.v2.TokenService/Revoke":                         {"*": true},
				"/metalstack.api.v2.TokenService/Update":                         {"*": true},
				"/metalstack.api.v2.UserService/Get":                             {"*": true},
				"/metalstack.api.v2.VersionService/Get":                          {"*": true},
			},
		},
		{
			name: "project roles with user token",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_USER,
				User:      "user-a",
			},
			projectsAndTenants: &repository.ProjectsAndTenants{
				ProjectRoles: map[string]apiv2.ProjectRole{
					"a": apiv2.ProjectRole_PROJECT_ROLE_VIEWER,
				},
			},
			want: tokenPermissions{
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      {"*": true},
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": {"*": true},
				"/metalstack.api.v2.FilesystemService/Get":                       {"*": true},
				"/metalstack.api.v2.FilesystemService/List":                      {"*": true},
				"/metalstack.api.v2.FilesystemService/Match":                     {"*": true},
				"/metalstack.api.v2.HealthService/Get":                           {"*": true},
				"/metalstack.api.v2.IPService/Get":                               {"a": true},
				"/metalstack.api.v2.IPService/List":                              {"a": true},
				"/metalstack.api.v2.ImageService/Get":                            {"*": true},
				"/metalstack.api.v2.ImageService/Latest":                         {"*": true},
				"/metalstack.api.v2.ImageService/List":                           {"*": true},
				"/metalstack.api.v2.MachineService/Get":                          {"a": true},
				"/metalstack.api.v2.MachineService/List":                         {"a": true},
				"/metalstack.api.v2.MethodService/List":                          {"*": true},
				"/metalstack.api.v2.MethodService/TokenScopedList":               {"*": true},
				"/metalstack.api.v2.NetworkService/Get":                          {"a": true},
				"/metalstack.api.v2.NetworkService/List":                         {"a": true},
				"/metalstack.api.v2.NetworkService/ListBaseNetworks":             {"a": true},
				"/metalstack.api.v2.PartitionService/Get":                        {"*": true},
				"/metalstack.api.v2.PartitionService/List":                       {"*": true},
				"/metalstack.api.v2.ProjectService/Get":                          {"a": true},
				"/metalstack.api.v2.ProjectService/InviteAccept":                 {"*": true},
				"/metalstack.api.v2.ProjectService/InviteGet":                    {"*": true},
				"/metalstack.api.v2.ProjectService/Leave":                        {"a": true},
				"/metalstack.api.v2.ProjectService/List":                         {"*": true},
				"/metalstack.api.v2.SizeService/Get":                             {"*": true},
				"/metalstack.api.v2.SizeService/List":                            {"*": true},
				"/metalstack.api.v2.TenantService/Create":                        {"*": true},
				"/metalstack.api.v2.TenantService/InviteAccept":                  {"*": true},
				"/metalstack.api.v2.TenantService/InviteGet":                     {"*": true},
				"/metalstack.api.v2.TenantService/List":                          {"*": true},
				"/metalstack.api.v2.TokenService/Create":                         {"*": true},
				"/metalstack.api.v2.TokenService/Get":                            {"*": true},
				"/metalstack.api.v2.TokenService/List":                           {"*": true},
				"/metalstack.api.v2.TokenService/Refresh":                        {"*": true},
				"/metalstack.api.v2.TokenService/Revoke":                         {"*": true},
				"/metalstack.api.v2.TokenService/Update":                         {"*": true},
				"/metalstack.api.v2.UserService/Get":                             {"*": true},
				"/metalstack.api.v2.VersionService/Get":                          {"*": true},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			a := &authorizer{
				log: slog.Default(),
			}
			a.projectsAndTenantsGetter = func(ctx context.Context, userId string) (*repository.ProjectsAndTenants, error) {
				if tt.projectsAndTenants == nil {
					return &repository.ProjectsAndTenants{}, nil
				}
				return tt.projectsAndTenants, nil
			}

			got, gotErr := a.getTokenPermissions(t.Context(), tt.token)
			if diff := cmp.Diff(got, tt.want); diff != "" {
				t.Errorf("diff = %s", diff)
			}

			if tt.wantErr != nil {
				require.EqualError(t, gotErr, tt.wantErr.Error())
			} else {
				require.NoError(t, gotErr)
			}
		})
	}
}
