package request

import (
	"context"
	"errors"
	"log/slog"
	"testing"

	"github.com/google/go-cmp/cmp"
	apiv2 "github.com/metal-stack/api/go/metalstack/api/v2"
	"github.com/metal-stack/api/go/metalstack/infra/v2/infrav2connect"
	"github.com/metal-stack/metal-apiserver/pkg/repository"
	"github.com/stretchr/testify/require"
)

func Test_getTokenPermissions(t *testing.T) {
	tests := []struct {
		name               string
		token              *apiv2.Token
		projectsAndTenants *repository.ProjectsAndTenants
		want               tokenPermissions
		wantErr            error
	}{
		{
			name:    "unknown admin role",
			token:   &apiv2.Token{User: "admin", AdminRole: apiv2.AdminRole_ADMIN_ROLE_UNSPECIFIED.Enum()},
			wantErr: errors.New("given admin role:ADMIN_ROLE_UNSPECIFIED is not valid"),
		},
		{
			name:  "empty token",
			token: nil,
			want: tokenPermissions{
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      {"*": {}},
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": {"*": {}},
				"/metalstack.api.v2.HealthService/Get":                           {"*": {}},
				"/metalstack.api.v2.MethodService/List":                          {"*": {}},
				"/metalstack.api.v2.VersionService/Get":                          {"*": {}},
			},
		},
		{
			name: "admin role editor",
			token: &apiv2.Token{
				User:      "admin",
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				AdminRole: apiv2.AdminRole_ADMIN_ROLE_EDITOR.Enum(),
			},
			want: tokenPermissions{
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      {"*": {}},
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": {"*": {}},
				"/metalstack.admin.v2.ComponentService/List":                     {"*": {}},
				"/metalstack.admin.v2.FilesystemService/Create":                  {"*": {}},
				"/metalstack.admin.v2.FilesystemService/Delete":                  {"*": {}},
				"/metalstack.admin.v2.FilesystemService/Update":                  {"*": {}},
				"/metalstack.admin.v2.IPService/List":                            {"*": {}},
				"/metalstack.admin.v2.ImageService/Create":                       {"*": {}},
				"/metalstack.admin.v2.ImageService/Delete":                       {"*": {}},
				"/metalstack.admin.v2.ImageService/Update":                       {"*": {}},
				"/metalstack.admin.v2.ImageService/Usage":                        {"*": {}},
				"/metalstack.admin.v2.MachineService/BMCCommand":                 {"*": {}},
				"/metalstack.admin.v2.MachineService/ConsolePassword":            {"*": {}},
				"/metalstack.admin.v2.MachineService/Get":                        {"*": {}},
				"/metalstack.admin.v2.MachineService/GetBMC":                     {"*": {}},
				"/metalstack.admin.v2.MachineService/List":                       {"*": {}},
				"/metalstack.admin.v2.MachineService/ListBMC":                    {"*": {}},
				"/metalstack.admin.v2.NetworkService/Create":                     {"*": {}},
				"/metalstack.admin.v2.NetworkService/Delete":                     {"*": {}},
				"/metalstack.admin.v2.NetworkService/Get":                        {"*": {}},
				"/metalstack.admin.v2.NetworkService/List":                       {"*": {}},
				"/metalstack.admin.v2.NetworkService/Update":                     {"*": {}},
				"/metalstack.admin.v2.PartitionService/Capacity":                 {"*": {}},
				"/metalstack.admin.v2.PartitionService/Create":                   {"*": {}},
				"/metalstack.admin.v2.PartitionService/Delete":                   {"*": {}},
				"/metalstack.admin.v2.PartitionService/Update":                   {"*": {}},
				"/metalstack.admin.v2.ProjectService/List":                       {"*": {}},
				"/metalstack.admin.v2.SizeReservationService/Create":             {"*": {}},
				"/metalstack.admin.v2.SizeReservationService/Delete":             {"*": {}},
				"/metalstack.admin.v2.SizeReservationService/List":               {"*": {}},
				"/metalstack.admin.v2.SizeReservationService/Update":             {"*": {}},
				"/metalstack.admin.v2.SizeService/Create":                        {"*": {}},
				"/metalstack.admin.v2.SizeService/Delete":                        {"*": {}},
				"/metalstack.admin.v2.SizeService/Update":                        {"*": {}},
				"/metalstack.admin.v2.SwitchService/Delete":                      {"*": {}},
				"/metalstack.admin.v2.SwitchService/Get":                         {"*": {}},
				"/metalstack.admin.v2.SwitchService/List":                        {"*": {}},
				"/metalstack.admin.v2.SwitchService/Migrate":                     {"*": {}},
				"/metalstack.admin.v2.SwitchService/Port":                        {"*": {}},
				"/metalstack.admin.v2.SwitchService/Update":                      {"*": {}},
				"/metalstack.admin.v2.TaskService/Delete":                        {"*": {}},
				"/metalstack.admin.v2.TaskService/Get":                           {"*": {}},
				"/metalstack.admin.v2.TaskService/List":                          {"*": {}},
				"/metalstack.admin.v2.TaskService/Queues":                        {"*": {}},
				"/metalstack.admin.v2.TenantService/Create":                      {"*": {}},
				"/metalstack.admin.v2.TenantService/List":                        {"*": {}},
				"/metalstack.admin.v2.TokenService/Create":                       {"*": {}},
				"/metalstack.admin.v2.TokenService/List":                         {"*": {}},
				"/metalstack.admin.v2.TokenService/Revoke":                       {"*": {}},
				"/metalstack.admin.v2.VPNService/AuthKey":                        {"*": {}},
				"/metalstack.admin.v2.VPNService/ListNodes":                      {"*": {}},
				"/metalstack.api.v2.FilesystemService/Get":                       {"*": {}},
				"/metalstack.api.v2.FilesystemService/List":                      {"*": {}},
				"/metalstack.api.v2.FilesystemService/Match":                     {"*": {}},
				"/metalstack.api.v2.HealthService/Get":                           {"*": {}},
				"/metalstack.api.v2.IPService/Create":                            {"*": {}},
				"/metalstack.api.v2.IPService/Delete":                            {"*": {}},
				"/metalstack.api.v2.IPService/Get":                               {"*": {}},
				"/metalstack.api.v2.IPService/List":                              {"*": {}},
				"/metalstack.api.v2.IPService/Update":                            {"*": {}},
				"/metalstack.api.v2.ImageService/Get":                            {"*": {}},
				"/metalstack.api.v2.ImageService/Latest":                         {"*": {}},
				"/metalstack.api.v2.ImageService/List":                           {"*": {}},
				"/metalstack.api.v2.MachineService/BMCCommand":                   {"*": {}},
				"/metalstack.api.v2.MachineService/Create":                       {"*": {}},
				"/metalstack.api.v2.MachineService/Delete":                       {"*": {}},
				"/metalstack.api.v2.MachineService/Get":                          {"*": {}},
				"/metalstack.api.v2.MachineService/GetBMC":                       {"*": {}},
				"/metalstack.api.v2.MachineService/List":                         {"*": {}},
				"/metalstack.api.v2.MachineService/Update":                       {"*": {}},
				"/metalstack.api.v2.MethodService/List":                          {"*": {}},
				"/metalstack.api.v2.MethodService/TokenScopedList":               {"*": {}},
				"/metalstack.api.v2.NetworkService/Create":                       {"*": {}},
				"/metalstack.api.v2.NetworkService/Delete":                       {"*": {}},
				"/metalstack.api.v2.NetworkService/Get":                          {"*": {}},
				"/metalstack.api.v2.NetworkService/List":                         {"*": {}},
				"/metalstack.api.v2.NetworkService/ListBaseNetworks":             {"*": {}},
				"/metalstack.api.v2.NetworkService/Update":                       {"*": {}},
				"/metalstack.api.v2.PartitionService/Get":                        {"*": {}},
				"/metalstack.api.v2.PartitionService/List":                       {"*": {}},
				"/metalstack.api.v2.ProjectService/Create":                       {"*": {}},
				"/metalstack.api.v2.ProjectService/Delete":                       {"*": {}},
				"/metalstack.api.v2.ProjectService/Get":                          {"*": {}},
				"/metalstack.api.v2.ProjectService/Invite":                       {"*": {}},
				"/metalstack.api.v2.ProjectService/InviteAccept":                 {"*": {}},
				"/metalstack.api.v2.ProjectService/InviteDelete":                 {"*": {}},
				"/metalstack.api.v2.ProjectService/InviteGet":                    {"*": {}},
				"/metalstack.api.v2.ProjectService/InvitesList":                  {"*": {}},
				"/metalstack.api.v2.ProjectService/Leave":                        {"*": {}},
				"/metalstack.api.v2.ProjectService/List":                         {"*": {}},
				"/metalstack.api.v2.ProjectService/RemoveMember":                 {"*": {}},
				"/metalstack.api.v2.ProjectService/Update":                       {"*": {}},
				"/metalstack.api.v2.ProjectService/UpdateMember":                 {"*": {}},
				"/metalstack.api.v2.SizeReservationService/Get":                  {"*": {}},
				"/metalstack.api.v2.SizeReservationService/List":                 {"*": {}},
				"/metalstack.api.v2.SizeService/Get":                             {"*": {}},
				"/metalstack.api.v2.SizeService/List":                            {"*": {}},
				"/metalstack.api.v2.TenantService/Create":                        {"*": {}},
				"/metalstack.api.v2.TenantService/Delete":                        {"*": {}},
				"/metalstack.api.v2.TenantService/Get":                           {"*": {}},
				"/metalstack.api.v2.TenantService/Invite":                        {"*": {}},
				"/metalstack.api.v2.TenantService/InviteAccept":                  {"*": {}},
				"/metalstack.api.v2.TenantService/InviteDelete":                  {"*": {}},
				"/metalstack.api.v2.TenantService/InviteGet":                     {"*": {}},
				"/metalstack.api.v2.TenantService/InvitesList":                   {"*": {}},
				"/metalstack.api.v2.TenantService/Leave":                         {"*": {}},
				"/metalstack.api.v2.TenantService/List":                          {"*": {}},
				"/metalstack.api.v2.TenantService/RemoveMember":                  {"*": {}},
				"/metalstack.api.v2.TenantService/Update":                        {"*": {}},
				"/metalstack.api.v2.TenantService/UpdateMember":                  {"*": {}},
				"/metalstack.api.v2.TokenService/Create":                         {"*": {}},
				"/metalstack.api.v2.TokenService/Get":                            {"*": {}},
				"/metalstack.api.v2.TokenService/List":                           {"*": {}},
				"/metalstack.api.v2.TokenService/Refresh":                        {"*": {}},
				"/metalstack.api.v2.TokenService/Revoke":                         {"*": {}},
				"/metalstack.api.v2.TokenService/Update":                         {"*": {}},
				"/metalstack.api.v2.UserService/Get":                             {"*": {}},
				"/metalstack.api.v2.VersionService/Get":                          {"*": {}},
				"/metalstack.infra.v2.BMCService/BMCCommandDone":                 {"*": {}},
				"/metalstack.infra.v2.BMCService/UpdateBMCInfo":                  {"*": {}},
				"/metalstack.infra.v2.BMCService/WaitForBMCCommand":              {"*": {}},
				"/metalstack.infra.v2.BootService/Boot":                          {"*": {}},
				"/metalstack.infra.v2.BootService/Dhcp":                          {"*": {}},
				"/metalstack.infra.v2.BootService/InstallationSucceeded":         {"*": {}},
				"/metalstack.infra.v2.BootService/Register":                      {"*": {}},
				"/metalstack.infra.v2.BootService/SuperUserPassword":             {"*": {}},
				"/metalstack.infra.v2.BootService/Wait":                          {"*": {}},
				"/metalstack.infra.v2.ComponentService/Ping":                     {"*": {}},
				"/metalstack.infra.v2.EventService/Send":                         {"*": {}},
				"/metalstack.infra.v2.SwitchService/Get":                         {"*": {}},
				"/metalstack.infra.v2.SwitchService/Heartbeat":                   {"*": {}},
				"/metalstack.infra.v2.SwitchService/Register":                    {"*": {}},
			},
			wantErr: nil,
		},
		{
			name: "admin role viewer",
			token: &apiv2.Token{
				User:      "admin",
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				AdminRole: apiv2.AdminRole_ADMIN_ROLE_VIEWER.Enum(),
			},
			want: tokenPermissions{
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      {"*": {}},
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": {"*": {}},
				"/metalstack.admin.v2.ComponentService/List":                     {"*": {}},
				"/metalstack.admin.v2.IPService/List":                            {"*": {}},
				"/metalstack.admin.v2.ImageService/Usage":                        {"*": {}},
				"/metalstack.admin.v2.MachineService/GetBMC":                     {"*": {}},
				"/metalstack.admin.v2.MachineService/ConsolePassword":            {"*": {}},
				"/metalstack.admin.v2.MachineService/Get":                        {"*": {}},
				"/metalstack.admin.v2.MachineService/List":                       {"*": {}},
				"/metalstack.admin.v2.MachineService/ListBMC":                    {"*": {}},
				"/metalstack.admin.v2.NetworkService/Get":                        {"*": {}},
				"/metalstack.admin.v2.NetworkService/List":                       {"*": {}},
				"/metalstack.admin.v2.PartitionService/Capacity":                 {"*": {}},
				"/metalstack.admin.v2.ProjectService/List":                       {"*": {}},
				"/metalstack.admin.v2.SizeReservationService/List":               {"*": {}},
				"/metalstack.admin.v2.SwitchService/Get":                         {"*": {}},
				"/metalstack.admin.v2.SwitchService/List":                        {"*": {}},
				"/metalstack.admin.v2.TaskService/Get":                           {"*": {}},
				"/metalstack.admin.v2.TaskService/List":                          {"*": {}},
				"/metalstack.admin.v2.TaskService/Queues":                        {"*": {}},
				"/metalstack.admin.v2.TenantService/List":                        {"*": {}},
				"/metalstack.admin.v2.TokenService/List":                         {"*": {}},
				"/metalstack.admin.v2.VPNService/ListNodes":                      {"*": {}},
				"/metalstack.api.v2.FilesystemService/Get":                       {"*": {}},
				"/metalstack.api.v2.FilesystemService/List":                      {"*": {}},
				"/metalstack.api.v2.FilesystemService/Match":                     {"*": {}},
				"/metalstack.api.v2.HealthService/Get":                           {"*": {}},
				"/metalstack.api.v2.IPService/Get":                               {"*": {}},
				"/metalstack.api.v2.IPService/List":                              {"*": {}},
				"/metalstack.api.v2.ImageService/Get":                            {"*": {}},
				"/metalstack.api.v2.ImageService/Latest":                         {"*": {}},
				"/metalstack.api.v2.ImageService/List":                           {"*": {}},
				"/metalstack.api.v2.MachineService/Get":                          {"*": {}},
				"/metalstack.api.v2.MachineService/List":                         {"*": {}},
				"/metalstack.api.v2.MethodService/List":                          {"*": {}},
				"/metalstack.api.v2.MethodService/TokenScopedList":               {"*": {}},
				"/metalstack.api.v2.NetworkService/Get":                          {"*": {}},
				"/metalstack.api.v2.NetworkService/List":                         {"*": {}},
				"/metalstack.api.v2.NetworkService/ListBaseNetworks":             {"*": {}},
				"/metalstack.api.v2.PartitionService/Get":                        {"*": {}},
				"/metalstack.api.v2.PartitionService/List":                       {"*": {}},
				"/metalstack.api.v2.ProjectService/Get":                          {"*": {}},
				"/metalstack.api.v2.ProjectService/InviteAccept":                 {"*": {}},
				"/metalstack.api.v2.ProjectService/InviteGet":                    {"*": {}},
				"/metalstack.api.v2.ProjectService/Leave":                        {"*": {}},
				"/metalstack.api.v2.ProjectService/List":                         {"*": {}},
				"/metalstack.api.v2.SizeReservationService/Get":                  {"*": {}},
				"/metalstack.api.v2.SizeReservationService/List":                 {"*": {}},
				"/metalstack.api.v2.SizeService/Get":                             {"*": {}},
				"/metalstack.api.v2.SizeService/List":                            {"*": {}},
				"/metalstack.api.v2.TenantService/Create":                        {"*": {}},
				"/metalstack.api.v2.TenantService/Get":                           {"*": {}},
				"/metalstack.api.v2.TenantService/InviteAccept":                  {"*": {}},
				"/metalstack.api.v2.TenantService/InviteGet":                     {"*": {}},
				"/metalstack.api.v2.TenantService/Leave":                         {"*": {}},
				"/metalstack.api.v2.TenantService/List":                          {"*": {}},
				"/metalstack.api.v2.TokenService/Create":                         {"*": {}},
				"/metalstack.api.v2.TokenService/Get":                            {"*": {}},
				"/metalstack.api.v2.TokenService/List":                           {"*": {}},
				"/metalstack.api.v2.TokenService/Refresh":                        {"*": {}},
				"/metalstack.api.v2.TokenService/Revoke":                         {"*": {}},
				"/metalstack.api.v2.TokenService/Update":                         {"*": {}},
				"/metalstack.api.v2.UserService/Get":                             {"*": {}},
				"/metalstack.api.v2.VersionService/Get":                          {"*": {}},
				"/metalstack.infra.v2.SwitchService/Get":                         {"*": {}},
			},
			wantErr: nil,
		},
		{
			name: "infra role editor",
			token: &apiv2.Token{
				User:      "metal-core",
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				InfraRole: apiv2.InfraRole_INFRA_ROLE_EDITOR.Enum(),
			},
			want: tokenPermissions{
				"/metalstack.infra.v2.BMCService/BMCCommandDone":    {"*": {}},
				"/metalstack.infra.v2.BMCService/UpdateBMCInfo":     {"*": {}},
				"/metalstack.infra.v2.BMCService/WaitForBMCCommand": {"*": {}},
				"/metalstack.infra.v2.BootService/Boot":             {"*": {}},
				"/metalstack.infra.v2.BootService/Dhcp":             {"*": {}},
				"/metalstack.infra.v2.ComponentService/Ping":        {"*": {}},
				"/metalstack.infra.v2.EventService/Send":            {"*": {}},
				"/metalstack.infra.v2.SwitchService/Get":            {"*": {}},
				"/metalstack.infra.v2.SwitchService/Heartbeat":      {"*": {}},
				"/metalstack.infra.v2.SwitchService/Register":       {"*": {}},
			},
		},
		{
			name: "infra role viewer",
			token: &apiv2.Token{
				User:      "metal-core",
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				InfraRole: apiv2.InfraRole_INFRA_ROLE_VIEWER.Enum(),
			},
			want: tokenPermissions{
				"/metalstack.infra.v2.SwitchService/Get": {"*": {}},
			},
		},
		{
			name: "only permissions",
			token: &apiv2.Token{
				User:      "user-a",
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				Permissions: []*apiv2.MethodPermission{
					{Subject: "a", Methods: []string{"/metalstack.api.v2.IPService/Create"}},
					{Subject: "a", Methods: []string{"/metalstack.api.v2.IPService/Delete"}},
					{Subject: "b", Methods: []string{"/metalstack.api.v2.IPService/Delete"}},
				},
			},
			projectsAndTenants: &repository.ProjectsAndTenants{
				ProjectRoles: map[string]apiv2.ProjectRole{
					"a": apiv2.ProjectRole_PROJECT_ROLE_EDITOR,
					"b": apiv2.ProjectRole_PROJECT_ROLE_OWNER,
				},
			},
			want: tokenPermissions{
				"/metalstack.api.v2.IPService/Create": {"a": {}},
				"/metalstack.api.v2.IPService/Delete": {"a": {}, "b": {}},
			},
		},
		{
			name: "infra permissions",
			token: &apiv2.Token{
				User: "metal-core",
				Permissions: []*apiv2.MethodPermission{
					{Subject: "*", Methods: []string{infrav2connect.SwitchServiceRegisterProcedure}},
				},
			},
			want: tokenPermissions{
				"/metalstack.infra.v2.SwitchService/Register": {"*": {}},
			},
		},
		{
			name: "tenant roles, token type api",
			token: &apiv2.Token{
				User:      "user-b",
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				TenantRoles: map[string]apiv2.TenantRole{
					"a": apiv2.TenantRole_TENANT_ROLE_GUEST,
					"b": apiv2.TenantRole_TENANT_ROLE_EDITOR,
					"c": apiv2.TenantRole_TENANT_ROLE_OWNER,
				},
			},
			projectsAndTenants: &repository.ProjectsAndTenants{
				TenantRoles: map[string]apiv2.TenantRole{
					"a": apiv2.TenantRole_TENANT_ROLE_GUEST,
					"b": apiv2.TenantRole_TENANT_ROLE_EDITOR,
					"c": apiv2.TenantRole_TENANT_ROLE_OWNER,
				},
			},
			want: tokenPermissions{
				"/metalstack.api.v2.ProjectService/Create":      {"b": {}, "c": {}},
				"/metalstack.api.v2.TenantService/Get":          {"b": {}, "a": {}, "c": {}},
				"/metalstack.api.v2.TenantService/Update":       {"b": {}, "c": {}},
				"/metalstack.api.v2.TenantService/Delete":       {"b": {}, "c": {}},
				"/metalstack.api.v2.TenantService/RemoveMember": {"c": {}},
				"/metalstack.api.v2.TenantService/UpdateMember": {"c": {}},
				"/metalstack.api.v2.TenantService/Invite":       {"c": {}},
				"/metalstack.api.v2.TenantService/InviteDelete": {"c": {}},
				"/metalstack.api.v2.TenantService/InvitesList":  {"c": {}},
			},
		},
		{
			name: "tenant roles, token type user",
			token: &apiv2.Token{
				User:      "user-b",
				TokenType: apiv2.TokenType_TOKEN_TYPE_USER,
			},
			projectsAndTenants: &repository.ProjectsAndTenants{
				TenantRoles: map[string]apiv2.TenantRole{
					"a": apiv2.TenantRole_TENANT_ROLE_GUEST,
					"b": apiv2.TenantRole_TENANT_ROLE_EDITOR,
					"c": apiv2.TenantRole_TENANT_ROLE_OWNER,
				},
			},
			want: tokenPermissions{
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      {"*": {}},
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": {"*": {}},
				"/metalstack.api.v2.FilesystemService/Get":                       {"*": {}},
				"/metalstack.api.v2.FilesystemService/List":                      {"*": {}},
				"/metalstack.api.v2.FilesystemService/Match":                     {"*": {}},
				"/metalstack.api.v2.HealthService/Get":                           {"*": {}},
				"/metalstack.api.v2.ImageService/Get":                            {"*": {}},
				"/metalstack.api.v2.ImageService/Latest":                         {"*": {}},
				"/metalstack.api.v2.ImageService/List":                           {"*": {}},
				"/metalstack.api.v2.MethodService/List":                          {"*": {}},
				"/metalstack.api.v2.MethodService/TokenScopedList":               {"*": {}},
				"/metalstack.api.v2.PartitionService/Get":                        {"*": {}},
				"/metalstack.api.v2.PartitionService/List":                       {"*": {}},
				"/metalstack.api.v2.ProjectService/Create":                       {"b": {}, "c": {}},
				"/metalstack.api.v2.ProjectService/InviteAccept":                 {"*": {}},
				"/metalstack.api.v2.ProjectService/InviteGet":                    {"*": {}},
				"/metalstack.api.v2.ProjectService/List":                         {"*": {}},
				"/metalstack.api.v2.SizeService/Get":                             {"*": {}},
				"/metalstack.api.v2.SizeService/List":                            {"*": {}},
				"/metalstack.api.v2.TenantService/Create":                        {"*": {}},
				"/metalstack.api.v2.TenantService/Get":                           {"b": {}, "a": {}, "c": {}},
				"/metalstack.api.v2.TenantService/Update":                        {"b": {}, "c": {}},
				"/metalstack.api.v2.TenantService/Delete":                        {"b": {}, "c": {}},
				"/metalstack.api.v2.TenantService/RemoveMember":                  {"c": {}},
				"/metalstack.api.v2.TenantService/UpdateMember":                  {"c": {}},
				"/metalstack.api.v2.TenantService/Invite":                        {"c": {}},
				"/metalstack.api.v2.TenantService/InviteAccept":                  {"*": {}},
				"/metalstack.api.v2.TenantService/InviteDelete":                  {"c": {}},
				"/metalstack.api.v2.TenantService/InviteGet":                     {"*": {}},
				"/metalstack.api.v2.TenantService/InvitesList":                   {"c": {}},
				"/metalstack.api.v2.TenantService/List":                          {"*": {}},
				"/metalstack.api.v2.TokenService/Create":                         {"*": {}},
				"/metalstack.api.v2.TokenService/Get":                            {"*": {}},
				"/metalstack.api.v2.TokenService/List":                           {"*": {}},
				"/metalstack.api.v2.TokenService/Refresh":                        {"*": {}},
				"/metalstack.api.v2.TokenService/Revoke":                         {"*": {}},
				"/metalstack.api.v2.TokenService/Update":                         {"*": {}},
				"/metalstack.api.v2.UserService/Get":                             {"*": {}},
				"/metalstack.api.v2.VersionService/Get":                          {"*": {}},
			},
		},
		{
			name: "project roles, token type api",
			token: &apiv2.Token{
				User:      "user-c",
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				ProjectRoles: map[string]apiv2.ProjectRole{
					"a": apiv2.ProjectRole_PROJECT_ROLE_VIEWER,
					"b": apiv2.ProjectRole_PROJECT_ROLE_EDITOR,
					"c": apiv2.ProjectRole_PROJECT_ROLE_OWNER,
				},
			},
			projectsAndTenants: &repository.ProjectsAndTenants{
				ProjectRoles: map[string]apiv2.ProjectRole{
					"a": apiv2.ProjectRole_PROJECT_ROLE_VIEWER,
					"b": apiv2.ProjectRole_PROJECT_ROLE_EDITOR,
					"c": apiv2.ProjectRole_PROJECT_ROLE_OWNER,
				},
			},
			want: tokenPermissions{
				"/metalstack.api.v2.IPService/Get":                   {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.IPService/Create":                {"b": {}, "c": {}},
				"/metalstack.api.v2.IPService/Update":                {"b": {}, "c": {}},
				"/metalstack.api.v2.IPService/List":                  {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.IPService/Delete":                {"b": {}, "c": {}},
				"/metalstack.api.v2.MachineService/BMCCommand":       {"b": {}, "c": {}},
				"/metalstack.api.v2.MachineService/Get":              {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.MachineService/GetBMC":           {"b": {}, "c": {}},
				"/metalstack.api.v2.MachineService/Create":           {"b": {}, "c": {}},
				"/metalstack.api.v2.MachineService/Update":           {"b": {}, "c": {}},
				"/metalstack.api.v2.MachineService/List":             {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.MachineService/Delete":           {"b": {}, "c": {}},
				"/metalstack.api.v2.NetworkService/Get":              {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.NetworkService/Create":           {"b": {}, "c": {}},
				"/metalstack.api.v2.NetworkService/Update":           {"b": {}, "c": {}},
				"/metalstack.api.v2.NetworkService/List":             {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.NetworkService/ListBaseNetworks": {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.NetworkService/Delete":           {"b": {}, "c": {}},
				"/metalstack.api.v2.ProjectService/Get":              {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.ProjectService/Delete":           {"c": {}},
				"/metalstack.api.v2.ProjectService/Update":           {"b": {}, "c": {}},
				"/metalstack.api.v2.ProjectService/RemoveMember":     {"c": {}},
				"/metalstack.api.v2.ProjectService/UpdateMember":     {"c": {}},
				"/metalstack.api.v2.ProjectService/Invite":           {"c": {}},
				"/metalstack.api.v2.ProjectService/InviteDelete":     {"c": {}},
				"/metalstack.api.v2.ProjectService/InvitesList":      {"c": {}},
				"/metalstack.api.v2.ProjectService/Leave":            {"a": {}},
				"/metalstack.api.v2.SizeReservationService/Get":      {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.SizeReservationService/List":     {"a": {}, "b": {}, "c": {}},
			},
		},
		{
			name: "project roles with user token",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_USER,
				User:      "user-a",
			},
			projectsAndTenants: &repository.ProjectsAndTenants{
				ProjectRoles: map[string]apiv2.ProjectRole{
					"a": apiv2.ProjectRole_PROJECT_ROLE_VIEWER,
					"b": apiv2.ProjectRole_PROJECT_ROLE_EDITOR,
					"c": apiv2.ProjectRole_PROJECT_ROLE_OWNER,
				},
			},
			want: tokenPermissions{
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      {"*": {}},
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": {"*": {}},
				"/metalstack.api.v2.FilesystemService/Get":                       {"*": {}},
				"/metalstack.api.v2.FilesystemService/List":                      {"*": {}},
				"/metalstack.api.v2.FilesystemService/Match":                     {"*": {}},
				"/metalstack.api.v2.HealthService/Get":                           {"*": {}},
				"/metalstack.api.v2.IPService/Get":                               {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.IPService/Create":                            {"b": {}, "c": {}},
				"/metalstack.api.v2.IPService/Update":                            {"b": {}, "c": {}},
				"/metalstack.api.v2.IPService/List":                              {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.IPService/Delete":                            {"b": {}, "c": {}},
				"/metalstack.api.v2.ImageService/Get":                            {"*": {}},
				"/metalstack.api.v2.ImageService/Latest":                         {"*": {}},
				"/metalstack.api.v2.ImageService/List":                           {"*": {}},
				"/metalstack.api.v2.MachineService/BMCCommand":                   {"b": {}, "c": {}},
				"/metalstack.api.v2.MachineService/Get":                          {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.MachineService/GetBMC":                       {"b": {}, "c": {}},
				"/metalstack.api.v2.MachineService/Create":                       {"b": {}, "c": {}},
				"/metalstack.api.v2.MachineService/Update":                       {"b": {}, "c": {}},
				"/metalstack.api.v2.MachineService/List":                         {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.MachineService/Delete":                       {"b": {}, "c": {}},
				"/metalstack.api.v2.MethodService/List":                          {"*": {}},
				"/metalstack.api.v2.MethodService/TokenScopedList":               {"*": {}},
				"/metalstack.api.v2.NetworkService/Get":                          {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.NetworkService/Create":                       {"b": {}, "c": {}},
				"/metalstack.api.v2.NetworkService/Update":                       {"b": {}, "c": {}},
				"/metalstack.api.v2.NetworkService/List":                         {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.NetworkService/ListBaseNetworks":             {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.NetworkService/Delete":                       {"b": {}, "c": {}},
				"/metalstack.api.v2.PartitionService/Get":                        {"*": {}},
				"/metalstack.api.v2.PartitionService/List":                       {"*": {}},
				"/metalstack.api.v2.ProjectService/Get":                          {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.ProjectService/Delete":                       {"c": {}},
				"/metalstack.api.v2.ProjectService/Update":                       {"b": {}, "c": {}},
				"/metalstack.api.v2.ProjectService/RemoveMember":                 {"c": {}},
				"/metalstack.api.v2.ProjectService/UpdateMember":                 {"c": {}},
				"/metalstack.api.v2.ProjectService/Invite":                       {"c": {}},
				"/metalstack.api.v2.ProjectService/InviteAccept":                 {"*": {}},
				"/metalstack.api.v2.ProjectService/InviteDelete":                 {"c": {}},
				"/metalstack.api.v2.ProjectService/InviteGet":                    {"*": {}},
				"/metalstack.api.v2.ProjectService/InvitesList":                  {"c": {}},
				"/metalstack.api.v2.ProjectService/Leave":                        {"a": {}},
				"/metalstack.api.v2.ProjectService/List":                         {"*": {}},
				"/metalstack.api.v2.SizeReservationService/Get":                  {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.SizeReservationService/List":                 {"a": {}, "b": {}, "c": {}},
				"/metalstack.api.v2.SizeService/Get":                             {"*": {}},
				"/metalstack.api.v2.SizeService/List":                            {"*": {}},
				"/metalstack.api.v2.TenantService/Create":                        {"*": {}},
				"/metalstack.api.v2.TenantService/InviteAccept":                  {"*": {}},
				"/metalstack.api.v2.TenantService/InviteGet":                     {"*": {}},
				"/metalstack.api.v2.TenantService/List":                          {"*": {}},
				"/metalstack.api.v2.TokenService/Create":                         {"*": {}},
				"/metalstack.api.v2.TokenService/Get":                            {"*": {}},
				"/metalstack.api.v2.TokenService/List":                           {"*": {}},
				"/metalstack.api.v2.TokenService/Refresh":                        {"*": {}},
				"/metalstack.api.v2.TokenService/Revoke":                         {"*": {}},
				"/metalstack.api.v2.TokenService/Update":                         {"*": {}},
				"/metalstack.api.v2.UserService/Get":                             {"*": {}},
				"/metalstack.api.v2.VersionService/Get":                          {"*": {}},
			},
		},
		{
			name: "project roles with user token",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_USER,
				User:      "user-a",
			},
			projectsAndTenants: &repository.ProjectsAndTenants{
				ProjectRoles: map[string]apiv2.ProjectRole{
					"a": apiv2.ProjectRole_PROJECT_ROLE_VIEWER,
				},
			},
			want: tokenPermissions{
				"/grpc.reflection.v1.ServerReflection/ServerReflectionInfo":      {"*": {}},
				"/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo": {"*": {}},
				"/metalstack.api.v2.FilesystemService/Get":                       {"*": {}},
				"/metalstack.api.v2.FilesystemService/List":                      {"*": {}},
				"/metalstack.api.v2.FilesystemService/Match":                     {"*": {}},
				"/metalstack.api.v2.HealthService/Get":                           {"*": {}},
				"/metalstack.api.v2.IPService/Get":                               {"a": {}},
				"/metalstack.api.v2.IPService/List":                              {"a": {}},
				"/metalstack.api.v2.ImageService/Get":                            {"*": {}},
				"/metalstack.api.v2.ImageService/Latest":                         {"*": {}},
				"/metalstack.api.v2.ImageService/List":                           {"*": {}},
				"/metalstack.api.v2.MachineService/Get":                          {"a": {}},
				"/metalstack.api.v2.MachineService/List":                         {"a": {}},
				"/metalstack.api.v2.MethodService/List":                          {"*": {}},
				"/metalstack.api.v2.MethodService/TokenScopedList":               {"*": {}},
				"/metalstack.api.v2.NetworkService/Get":                          {"a": {}},
				"/metalstack.api.v2.NetworkService/List":                         {"a": {}},
				"/metalstack.api.v2.NetworkService/ListBaseNetworks":             {"a": {}},
				"/metalstack.api.v2.PartitionService/Get":                        {"*": {}},
				"/metalstack.api.v2.PartitionService/List":                       {"*": {}},
				"/metalstack.api.v2.ProjectService/Get":                          {"a": {}},
				"/metalstack.api.v2.ProjectService/InviteAccept":                 {"*": {}},
				"/metalstack.api.v2.ProjectService/InviteGet":                    {"*": {}},
				"/metalstack.api.v2.ProjectService/Leave":                        {"a": {}},
				"/metalstack.api.v2.ProjectService/List":                         {"*": {}},
				"/metalstack.api.v2.SizeReservationService/Get":                  {"a": {}},
				"/metalstack.api.v2.SizeReservationService/List":                 {"a": {}},
				"/metalstack.api.v2.SizeService/Get":                             {"*": {}},
				"/metalstack.api.v2.SizeService/List":                            {"*": {}},
				"/metalstack.api.v2.TenantService/Create":                        {"*": {}},
				"/metalstack.api.v2.TenantService/InviteAccept":                  {"*": {}},
				"/metalstack.api.v2.TenantService/InviteGet":                     {"*": {}},
				"/metalstack.api.v2.TenantService/List":                          {"*": {}},
				"/metalstack.api.v2.TokenService/Create":                         {"*": {}},
				"/metalstack.api.v2.TokenService/Get":                            {"*": {}},
				"/metalstack.api.v2.TokenService/List":                           {"*": {}},
				"/metalstack.api.v2.TokenService/Refresh":                        {"*": {}},
				"/metalstack.api.v2.TokenService/Revoke":                         {"*": {}},
				"/metalstack.api.v2.TokenService/Update":                         {"*": {}},
				"/metalstack.api.v2.UserService/Get":                             {"*": {}},
				"/metalstack.api.v2.VersionService/Get":                          {"*": {}},
			},
		},
		{
			name: "project roles with api token and permission",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				User:      "user-a",
				Permissions: []*apiv2.MethodPermission{
					{
						Subject: "*",
						Methods: []string{"/metalstack.api.v2.MachineService/Create"},
					},
				},
			},
			projectsAndTenants: &repository.ProjectsAndTenants{
				Projects: []*apiv2.Project{
					{Uuid: "a"},
					{Uuid: "b"},
				},
				ProjectRoles: map[string]apiv2.ProjectRole{
					"a": apiv2.ProjectRole_PROJECT_ROLE_VIEWER,
					"b": apiv2.ProjectRole_PROJECT_ROLE_EDITOR,
				},
			},
			want: tokenPermissions{
				"/metalstack.api.v2.MachineService/Create": {"b": {}},
			},
		},
		{
			name: "tenant roles with api token and permission",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				User:      "user-a",
				Permissions: []*apiv2.MethodPermission{
					{
						Subject: "*",
						Methods: []string{"/metalstack.api.v2.ProjectService/Create"},
					},
				},
			},
			projectsAndTenants: &repository.ProjectsAndTenants{
				Tenants: []*apiv2.Tenant{
					{Login: "user-a"},
				},
				TenantRoles: map[string]apiv2.TenantRole{
					"user-a": apiv2.TenantRole_TENANT_ROLE_EDITOR,
				},
			},
			want: tokenPermissions{
				"/metalstack.api.v2.ProjectService/Create": {"user-a": {}},
			},
		},
		{
			name: "tenant roles api tokens and permissions subject does not exist",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				User:      "user-a",
				Permissions: []*apiv2.MethodPermission{
					{
						Subject: "foo",
						Methods: []string{"/metalstack.api.v2.ProjectService/Create"},
					},
					{
						Subject: "*",
						Methods: []string{"/metalstack.api.v2.ProjectService/Create"},
					},
				},
			},
			projectsAndTenants: &repository.ProjectsAndTenants{
				Tenants: []*apiv2.Tenant{
					{Login: "user-a"},
				},
				TenantRoles: map[string]apiv2.TenantRole{
					"user-a": apiv2.TenantRole_TENANT_ROLE_EDITOR,
				},
			},
			want: tokenPermissions{
				"/metalstack.api.v2.ProjectService/Create": {"user-a": {}},
			},
		},
		{
			name: "project roles api tokens and permissions subject does not exist",
			token: &apiv2.Token{
				TokenType: apiv2.TokenType_TOKEN_TYPE_API,
				User:      "user-a",
				Permissions: []*apiv2.MethodPermission{
					{
						Subject: "foo",
						Methods: []string{"/metalstack.api.v2.MachineService/Create"},
					},
					{
						Subject: "project-a",
						Methods: []string{"/metalstack.api.v2.MachineService/Create"},
					},
				},
			},
			projectsAndTenants: &repository.ProjectsAndTenants{
				Projects: []*apiv2.Project{
					{Uuid: "project-a"},
				},
				ProjectRoles: map[string]apiv2.ProjectRole{
					"project-a": apiv2.ProjectRole_PROJECT_ROLE_EDITOR,
				},
			},
			want: tokenPermissions{
				"/metalstack.api.v2.MachineService/Create": {"project-a": {}},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			a := &authorizer{
				log: slog.Default(),
			}
			a.projectsAndTenantsGetter = func(ctx context.Context, userId string) (*repository.ProjectsAndTenants, error) {
				if tt.projectsAndTenants == nil {
					return &repository.ProjectsAndTenants{}, nil
				}
				return tt.projectsAndTenants, nil
			}

			got, gotErr := a.getTokenPermissions(t.Context(), tt.token)
			if diff := cmp.Diff(tt.want, got); diff != "" {
				t.Errorf("diff = %s", diff)
			}

			if tt.wantErr != nil {
				require.EqualError(t, gotErr, tt.wantErr.Error())
			} else {
				require.NoError(t, gotErr)
			}
		})
	}
}
