---
name: Docker Build Action
on:
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go 1.25
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          check-latest: true
          cache: false

      - name: Lint Go
        uses: golangci/golangci-lint-action@v8

      - uses: StyraInc/setup-regal@v1
        with:
          version: latest

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Build
        run: |
          make
      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # optional (default = false)

  build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go 1.25
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          check-latest: true
          cache: false

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build
        run: |
          make server

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}

  bench:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.25
      uses: actions/setup-go@v6
      with:
        go-version: "1.25"
        cache: false
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: run benchmark
      run: |
        make bench | tee output.txt

    - name: Download previous benchmark data
      uses: actions/cache@v4
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'go'
        output-file-path: output.txt
        external-data-json-path: ./cache/benchmark-data.json
         # GitHub API token to make a commit comment
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fail-on-alert: true
